automated dev commit

diff --git a/scripts/git-pullmaster b/scripts/git-pullmaster
--- a/scripts/git-pullmaster
+++ b/scripts/git-pullmaster
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -euo pipefail
+
 BLUE='\033[0;34m'
 GREEN='\033[0;32m'
 NO_COLOR='\033[0m'
@@ -27,7 +29,7 @@ for repo_dir in "${!unique_repos[@]}"; do
     branch_name=$(git rev-parse --abbrev-ref HEAD)
 
     echo -e "Pulling in ${BLUE}${repo_name}${NO_COLOR} on branch ${GREEN}${branch_name}${NO_COLOR}"
-    git pull
+    git pull || echo -e "\033[0;31mFailed to pull ${repo_name}\033[0m"
 
     cd - > /dev/null || exit 1
 done
